server:
  port: 8888
  error:
    include-message: always
    include-binding-errors: always
    
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermgmt
    username: root
    password: Temp@123
  jpa: 
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
        format_sql: true
    show-sql: true